services:
  db:
    container_name: ${PROJECT}-db
    image: postgres:latest
    restart: always
    env_file: ./docker.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    ports:
      - "54320:5432"
  server:
    image: ${PROJECT}-server
    container_name: ${PROJECT}-server
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./docker.env
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
    networks:
      - default